### ISSUE TITLE
ES6 관련 오류

### ISSUE THREAD

**Issue by sanha** [RaySuhyunLee/SNUCMS-Plus#36]
노트북 환경에서 es6가 적용된 브랜치에 rake를 실행하면 다음과 같은 오류가 납니다.

``````
sanha@ubuntu:~/SNUCMS-Plus$ rake -v
rake aborted!
NoMethodError: undefined method `register_engine' for Sprockets:Module
/usr/local/rvm/gems/ruby-2.2.3/gems/sprockets-es6-0.9.0/lib/sprockets/es6.rb:90:in `<module:Sprockets>'
/usr/local/rvm/gems/ruby-2.2.3/gems/sprockets-es6-0.9.0/lib/sprockets/es6.rb:6:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `require'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `rescue in block in require'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:68:in `block in require'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/home/sanha/SNUCMS-Plus/config/application.rb:7:in `<top (required)>'
/home/sanha/SNUCMS-Plus/Rakefile:4:in `requ
```ire'
/home/sanha/SNUCMS-Plus/Rakefile:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
LoadError: cannot load such file -- sprockets-es6
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/home/sanha/SNUCMS-Plus/config/application.rb:7:in `<top (required)>'
/home/sanha/SNUCMS-Plus/Rakefile:4:in `require'
/home/sanha/SNUCMS-Plus/Rakefile:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
``````

우선 gemfile에서 es6를 주석처리하고 진행중입니다. 한 번 확인해주세요.

**Comment by raysuhyunlee** [comment]
mac에서 실행할 때는 서버가 정상적으로 작동하는 것을 확인했습니다. 해당 라이브러리가 우분투 환경 상에서 문제가 있는지 확인해볼 필요가 있을 것 같습니다.

**Comment by sanha** [comment]
잉 근데 같은 환경의 데스크탑에서는 문제없이 실행되네요

**Comment by raysuhyunlee** [comment]
~~이슈의 부활!~~
그런거 없다

**Comment by raysuhyunlee** [comment]
Sprockets version 4.0.0.beta2에서 위에 산하가 말한 오류가 발생. stable한 3.6.0으로 바꾸겠습니다.
